name: statdb-cli
version: 0.1.0.0
license: MIT
author: "6.826 staff"
copyright: "2019 6.826 staff"

description: Please see the labs README

dependencies:
  - base >= 4.7 && < 5
  - ghc-prim
  - mtl
  - bytestring

executables:
  statdb-cli:
    main: Main.hs
    source-dirs:
      - lib
      - extract
